version: '3.7'

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        hostname: mariadb-container
        environment:
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        ports:
            - "${MARIADB_PORT}:3306"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/mariadb/data:/var/lib/mysql
            - /etc/thehand/mariadb:/etc/mysql
        restart: always
        networks:
            - thehandnetback

    mariadb-backup:
        image: databack/mysql-backup:latest
        container_name: mariadb-backup
        hostname: mariadb-backup-container
        volumes:
            - /opt/mariadb/backup:/db
        environment:
            - DB_SERVER=mariadb.mariadb_backup
            - DB_PORT=${MARIADB_PORT}
            - DB_USER=root
            - DB_PASS=${MARIADB_ROOT_PASSWORD}
            - DB_DUMP_CRON= 0 4 * * * 
        restart: always
        networks:
            - thehandnetback

    rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
        hostname: rabbitmq-container
        ports:
            - "${RABBITMQ_PORT}:5671" # rabbitmq-plugins enable rabbitmq_auth_mechanism_ssl
        volumes:
            - /etc/thehand/rabbitmq:/etc/rabbitmq
        restart: always
        networks:
            - thehandnetback

networks:
    thehandnetback:
        internal: true
        name: thehandnetback