version: '2'

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/mariadb/data:/var/lib/mysql
        restart: always
        networks:
            - mariadb_backup
            - mariadb_telegram

networks:
    mariadb_telegram:
        external: true
    mariadb_backup:
        external: true
