version: '3.7'

services:
    thehand:
        image: alessandrograssi/thehand:latest
        container_name: {CONTAINER_NAME}
        hostname: thehand-container
        volumes:
            - /etc/thehand/telegram/{CONTAINER_NAME}:/etc/thehand
            - /etc/thehand/telegram:/opt/thehand
        restart: always
        networks:
            - thehandnetback

networks:
    telegram_mariadb:
        external: true
    telegram_rabbitmq:
        external: true
