version: '2'

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/mariadb/data:/var/lib/mysql
        restart: always

    mariadb-backup:
        image: databack/mysql-backup:latest
        container_name: mariadb-backup
        volumes:
            - /opt/mariadb/backup:/db
        environment:
            - DB_SERVER=${MARIADB_HOST}
            - DB_PORT=${MARIADB_PORT}
            - DB_USER=root
            - DB_PASS=${MARIADB_ROOT_PASSWORD}
            - DB_DUMP_CRON= 0 4 * * * 
        restart: always
